apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
    # ODF-LVM should not attempt to manage openshift or kube infra namespaces
    topolvm.cybozu.com/webhook: "ignore"
  name: openshift-controller-manager
