apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  annotations:
    openshift.io/node-selector: ""
    workload.openshift.io/allowed: "management"
  labels:
    # ODF-LVM should not attempt to manage openshift or kube infra namespaces
    topolvm.cybozu.com/webhook: "ignore"