apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: topolvm-controller
  namespace: openshift-storage
rules:
  - apiGroups:
      - ""
    resources:
      - configMaps
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create