apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-operator
  namespace: openshift-dns-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dns-operator
  template:
    metadata:
      labels:
        name: dns-operator
    spec:
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
        #node-role.kubernetes.io/master: ''
      restartPolicy: Always
      priorityClassName: system-cluster-critical
      serviceAccountName: dns-operator
      containers:
      - name: dns-operator
        terminationMessagePolicy: FallbackToLogsOnError
        image: {{.ImageDNSOperator}}
        command:
        - dns-operator
        env:
        - name: RELEASE_VERSION
          value: {{.VersionDNSOperator}}
        - name: IMAGE
          value: {{.ImageCoreDNS}}
        - name: OPENSHIFT_CLI_IMAGE
          value: {{.ImageOC}}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: {{.ImageKubeRbacProxy}}
        resources:
          requests:
            cpu: 10m
      - name: kube-rbac-proxy
        image: {{.ImageKubeRbacProxy}}
        args:
        - --logtostderr
        - --insecure-listen-address=:9393
        - --upstream=http://127.0.0.1:60000/
        ports:
        - containerPort: 9393
          name: metrics
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      terminationGracePeriodSeconds: 2
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      
