---
# setup-microshift-host tasks

- name: install firewalld & packages
  ansible.builtin.dnf:
    name: "{{ install_packages }}"
    state: present
    update_cache: true

# Install go1.18
# This is installed into different location (/usr/local/bin/go) from dnf installed Go (/usr/bin/go) so it doesn't conflict
# /usr/local/bin is before /usr/bin in $PATH so newer one is picked up
# To be removed when go1.18 is available in repositories
- name: install golang
  ansible.builtin.shell: |
    export GO_VER=1.18.7
    curl -L -o go${GO_VER}.linux-amd64.tar.gz https://go.dev/dl/go${GO_VER}.linux-amd64.tar.gz &&
        sudo rm -rf /usr/local/go${GO_VER} && \
        sudo mkdir -p /usr/local/go${GO_VER} && \
        sudo tar -C /usr/local/go${GO_VER} -xzf go${GO_VER}.linux-amd64.tar.gz --strip-components 1 && \
        sudo rm -rfv /usr/local/bin/{go,gofmt}
        sudo ln --symbolic /usr/local/go1.18.7/bin/go /usr/local/go1.18.7/bin/gofmt /usr/local/bin/ && \
        rm -rfv go${GO_VER}.linux-amd64.tar.gz

- name: start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: check if rhel vg exists
  ansible.builtin.command: vgdisplay -s {{ vg_name }}
  register: rhel_vg_present
  ignore_errors: true

- name: create a volume group on top of secondary disk for topolvm
  community.general.lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ lvm_disk }}"
  when: rhel_vg_present.rc != 0

- name: upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  notify: reboot machine

- name: flush handlers
  ansible.builtin.meta: flush_handlers
