apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.authorization.openshift.io
spec:
  group: authorization.openshift.io
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
