---
# install-logging tasks

- name: rpm tasks
  block:
    - name: install prometheus
      ansible.builtin.dnf:
        name: golang-github-prometheus
        state: present
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat") or (ansible_distribution == "Fedora")

- name: copy prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    backup: true

- name: start and enable prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
