---
# install-logging tasks

- name: rpm tasks
  block:
    - name: install prometheus & grafana
      ansible.builtin.dnf:
        name: "{{ logging_packages }}"
        state: present
        update_cache: true
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat") or (ansible_distribution == "Fedora")

- name: copy prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    backup: true

- name: start and enable prometheus & grafana service(s)
  ansible.builtin.systemd:
    name: "{{ logging_services }}"
    state: restarted
    enabled: yes
