manage_subscription: false
rhel_username:
rhel_password:
rhel_pool_id:

prometheus_logging: true
setup_microshift_host: false
build_etcd_binary: false

install_pbench: false
pbench_configuration_environment: ec2
pbench_key_url:
pbench_config_url:
pbench_record_duration: 360
