manage_subscription: false
rhel_username:
rhel_password:
rhel_pool_id:

prometheus_logging: false

install_pbench: true
pbench_configuration_environment: ec2
pbench_key_url:
pbench_config_url:
pbench_record_duration: 360

setup_microshift_host: false
build_etcd_binary: false
