---
# install-microshift default vars

etcd_dir: "{{ ansible_env.HOME }}/etcd"
etcd_repo: https://github.com/openshift/etcd.git

microshift_dir: "{{ ansible_env.HOME }}/microshift"
microshift_repo: https://github.com/openshift/microshift.git
microshift_rpms: []

remote_kubeconfig_path: /var/lib/microshift/resources/kubeadmin/kubeconfig

du_dirs:
  - /
  - /var/
  - /var/lib/
  - /var/lib/containers/storage/
  - /usr/
  - /usr/bin/*

sample_interval: 5
